/**
 * Enumeration with the reserved words
 */
export enum ReservedWord {
  ARIT = 'arit',
  ASSIGNMENT = 'assignment',
  ADJUST = 'adjust',
  ADJUST_INIT = 'adjustInit',
  BOOLEAN = 'boolean',
  BREAK = 'break',
  CHAR = 'char',
  CYCLE = 'cycle',
  CONTINUE = 'continue',
  DECIMAL = 'decimal',
  DOWN = 'down',
  END_PROJECT = 'EndProject',
  FALSE = 'false',
  FUNCTION = 'function',
  INT = 'int',
  LOG = 'log',
  IMMUTABLE = 'InMut',
  MUTABLE = 'Mut',
  OTHER = 'other',
  ORIGINATE = 'originate',
  READ = 'read',
  REL = 'rel',
  PRINT = 'print',
  PRIVATE = 'private',
  PUBLIC = 'public',
  TURN = 'turn',
  START_PROJECT = 'StrProject',
  STRING = 'string',
  TRUE = 'true',
  UP = 'up',
  VOID = 'void',
  WHEN = 'when',
}
